version: "3.7"

services:
  database:
    image: postgres
    container_name: quakelogdb
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=quakelogdb
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: quakelogparser
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
	    - database
    depends_on: 
	    - database

volumes:
  pgdata:
    driver: local